import Link from "next/link";

/* ── Data ──────────────────────────────────────────────── */
const STATS = [
  { num: "0%",     label: "On-chain exposure" },
  { num: "100%",   label: "Shielded by default" },
  { num: "∞",      label: "Recipients per run" },
] as const;

const STEPS = [
  {
    num: "01",
    title: "Upload your payroll CSV",
    desc: "Drag in your roster — wallet addresses, amounts, and token types. Every address is validated on-curve before a single transaction fires.",
  },
  {
    num: "02",
    title: "Send privately via Cloak",
    desc: "One click triggers a shielded batch disbursement. On-chain it appears as a single opaque transaction — no readable output amounts, no salary leaks.",
  },
  {
    num: "03",
    title: "Export the viewing key",
    desc: "After disbursing, download a cryptographic viewing key. Paste it in the Audit page anytime to unlock the full breakdown — no wallet required.",
  },
] as const;

const PLATFORM = [
  {
    tag: "Payroll",
    title: "Payroll Dashboard",
    desc: "Upload a CSV roster, validate every wallet address on-curve, review amounts per token, then fire a shielded batch disbursement to your entire team in one click.",
    href: "/dashboard",
    cta: "Launch Dashboard",
  },
  {
    tag: "Compliance",
    title: "Viewing Key Audit",
    desc: "Paste a viewing key to decrypt any past batch in full. Recipient wallets, individual amounts, timestamps — everything your accountant needs. No Solana wallet required.",
    href: "/audit",
    cta: "Open Audit",
  },
  {
    tag: "Contributor",
    title: "My Payments",
    desc: "Each contributor connects their wallet and sees only their own payment history. No cross-visibility, no salary gossip, no leaking batch metadata to teammates.",
    href: "/contributor",
    cta: "View Payments",
  },
  {
    tag: "Protocol",
    title: "Cloak Privacy Layer",
    desc: "Every disbursement routes through fresh stealth addresses generated by Cloak SDK. On-chain it reads as a single opaque instruction — provably private, no custom crypto needed.",
    href: "/dashboard",
    cta: "Get Started",
  },
] as const;

/* ── Page ──────────────────────────────────────────────── */
export default function LandingPage() {
  return (
    <div className="relative overflow-x-hidden">
      {/* Background grid */}
      <div className="absolute inset-0 bg-grid pointer-events-none select-none" aria-hidden="true" />

      {/* Floating orbs */}
      <div
        className="orb absolute pointer-events-none"
        style={{ top: "-200px", left: "15%", width: "800px", height: "800px", borderRadius: "50%", background: "radial-gradient(circle, rgba(109,40,217,0.22) 0%, transparent 65%)" }}
        aria-hidden="true"
      />
      <div
        className="orb orb-2 absolute pointer-events-none"
        style={{ bottom: "-100px", right: "5%", width: "550px", height: "550px", borderRadius: "50%", background: "radial-gradient(circle, rgba(139,92,246,0.15) 0%, transparent 65%)" }}
        aria-hidden="true"
      />

      {/* ──────────────── HERO ──────────────── */}
      <section className="relative z-10 max-w-5xl mx-auto px-4 pt-28 pb-20 text-center">
        {/* Live badge */}
        <div className="badge mb-10 mx-auto w-fit" role="status">
          <span
            className="w-2 h-2 rounded-full block"
            style={{ background: "#a78bfa" }}
            aria-hidden="true"
          />
          Live on Solana Devnet&nbsp;&nbsp;·&nbsp;&nbsp;Powered by Cloak Protocol
        </div>

        {/* Headline */}
        <h1
          className="font-extrabold tracking-tight leading-none mb-6"
          style={{ fontSize: "clamp(3rem, 9vw, 5.5rem)", letterSpacing: "-0.02em" }}
        >
          <span className="text-white">Pay Your Team.</span>
          <br />
          <span className="gradient-text">Privately.</span>
        </h1>

        {/* Sub */}
        <p className="text-slate-400 text-lg sm:text-xl max-w-2xl mx-auto mb-10 leading-relaxed">
          On a transparent chain, every contributor can see every colleague&apos;s salary.{" "}
          <span className="text-white font-semibold">Shieldrexx</span> fixes that —
          zero-knowledge batch disbursements, private by default, auditable by choice.
        </p>

        {/* CTAs */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center mb-20">
          <Link href="/dashboard" className="btn-primary">
            Launch Payroll Run <span aria-hidden="true">→</span>
          </Link>
          <Link href="/audit" className="btn-secondary">
            Audit a Batch
          </Link>
        </div>

        {/* Stats strip */}
        <div
          className="inline-grid grid-cols-3 rounded-2xl overflow-hidden border w-full max-w-xl mx-auto"
          style={{ borderColor: "rgba(124,58,237,0.25)", background: "rgba(109,40,217,0.07)" }}
          role="list"
          aria-label="Key metrics"
        >
          {STATS.map((s, i) => (
            <div
              key={s.label}
              className="px-6 py-6"
              role="listitem"
              style={i > 0 ? { borderLeft: "1px solid rgba(124,58,237,0.2)" } : undefined}
            >
              <p className="text-3xl font-bold gradient-text">{s.num}</p>
              <p className="text-slate-500 text-xs mt-1.5 leading-snug">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ──────────── HOW IT WORKS ──────────── */}
      <section className="relative z-10 max-w-5xl mx-auto px-4 pb-28" aria-labelledby="how-h">
        <div className="mb-14">
          <p className="step-num uppercase tracking-widest mb-4">How it works</p>
          <h2 id="how-h" className="text-3xl sm:text-4xl font-bold text-white leading-tight">
            From upload to payout
            <br />
            <span className="gradient-text">in seconds.</span>
          </h2>
        </div>

        <div className="flex flex-col gap-5">
          {STEPS.map(({ num, title, desc }) => (
            <div
              key={num}
              className="card rounded-2xl p-7 flex items-start gap-6"
            >
              <div
                className="shrink-0 w-12 h-12 rounded-xl flex items-center justify-center"
                style={{ background: "rgba(40,20,80,0.9)", border: "1px solid rgba(124,58,237,0.45)", boxShadow: "0 0 20px rgba(124,58,237,0.2)" }}
                aria-label={`Step ${num}`}
              >
                <span className="step-num text-sm">{num}</span>
              </div>
              <div>
                <h3 className="text-white font-semibold text-base mb-1.5">{title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ─────────────── PLATFORM ─────────────── */}
      <section className="relative z-10 max-w-5xl mx-auto px-4 pb-28" aria-labelledby="platform-h">
        <div className="mb-14">
          <p className="step-num uppercase tracking-widest mb-4">Platform</p>
          <h2 id="platform-h" className="text-3xl sm:text-4xl font-bold text-white leading-tight">
            Everything you need to
            <br />
            <span className="gradient-text">pay privately.</span>
          </h2>
        </div>

        <div className="grid sm:grid-cols-2 gap-5">
          {PLATFORM.map(({ tag, title, desc, href, cta }) => (
            <Link
              key={title}
              href={href}
              className="card rounded-2xl p-8 flex flex-col gap-4 group no-underline"
              aria-label={title}
            >
              <div>
                <span className="step-num uppercase tracking-widest block mb-3">{tag}</span>
                <h3 className="text-white font-bold text-xl mb-3 leading-snug">{title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{desc}</p>
              </div>
              <div className="mt-auto pt-2">
                <span
                  className="inline-flex items-center gap-2 text-sm font-semibold transition-all duration-200"
                  style={{ color: "#a78bfa" }}
                >
                  {cta}
                  <span
                    className="transition-transform duration-200 group-hover:translate-x-1"
                    aria-hidden="true"
                  >
                    →
                  </span>
                </span>
              </div>
            </Link>
          ))}
        </div>
      </section>

      {/* ─────────────── BOTTOM CTA ─────────────── */}
      <section className="relative z-10 max-w-5xl mx-auto px-4 pb-32">
        <div
          className="card rounded-3xl p-12 sm:p-20 text-center"
          style={{ background: "linear-gradient(135deg, rgba(13,18,48,0.98) 0%, rgba(50,20,90,0.45) 100%)" }}
        >
          <p className="step-num uppercase tracking-widest mb-5">Get started</p>
          <h2
            className="font-extrabold text-white mb-4 leading-tight"
            style={{ fontSize: "clamp(2rem, 5vw, 3.2rem)", letterSpacing: "-0.02em" }}
          >
            Private by default.
            <br />
            <span className="gradient-text">Auditable by choice.</span>
          </h2>
          <p className="text-slate-400 max-w-md mx-auto mb-10 leading-relaxed">
            Connect your Phantom wallet on Devnet and run a full shielded batch
            disbursement in under two minutes. The viewing key stays with you.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/dashboard" className="btn-primary">
              Launch Payroll Run <span aria-hidden="true">→</span>
            </Link>
            <Link href="/contributor" className="btn-secondary">
              View My Payments
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
