import Link from "next/link";

/* ── Inline SVG icons ──────────────────────────────────── */
function IconLock() {
  return (
    <svg viewBox="0 0 24 24" fill="none" className="w-5 h-5" aria-hidden="true">
      <rect x="5" y="11" width="14" height="10" rx="2" fill="url(#lk)" />
      <path
        d="M8 11V7a4 4 0 0 1 8 0v4"
        stroke="url(#lk)"
        strokeWidth="1.5"
        strokeLinecap="round"
      />
      <circle cx="12" cy="16" r="1.5" fill="white" />
      <defs>
        <linearGradient id="lk" x1="5" y1="1" x2="19" y2="21" gradientUnits="userSpaceOnUse">
          <stop stopColor="#c4b5fd" />
          <stop offset="1" stopColor="#7c3aed" />
        </linearGradient>
      </defs>
    </svg>
  );
}

function IconKey() {
  return (
    <svg viewBox="0 0 24 24" fill="none" className="w-5 h-5" aria-hidden="true">
      <circle cx="9" cy="12" r="5" stroke="url(#ky)" strokeWidth="1.5" />
      <path
        d="M14 10.5H22M19 10.5V14"
        stroke="url(#ky)"
        strokeWidth="1.5"
        strokeLinecap="round"
      />
      <circle cx="9" cy="12" r="2" fill="url(#ky)" />
      <defs>
        <linearGradient id="ky" x1="3" y1="7" x2="22" y2="17" gradientUnits="userSpaceOnUse">
          <stop stopColor="#c4b5fd" />
          <stop offset="1" stopColor="#7c3aed" />
        </linearGradient>
      </defs>
    </svg>
  );
}

function IconBolt() {
  return (
    <svg viewBox="0 0 24 24" fill="none" className="w-5 h-5" aria-hidden="true">
      <path d="M13 2L4 14h8l-1 8 9-12h-8l1-8z" fill="url(#bt)" />
      <defs>
        <linearGradient id="bt" x1="4" y1="2" x2="21" y2="22" gradientUnits="userSpaceOnUse">
          <stop stopColor="#c4b5fd" />
          <stop offset="1" stopColor="#7c3aed" />
        </linearGradient>
      </defs>
    </svg>
  );
}

/* ── Data ──────────────────────────────────────────────── */
const FEATURES = [
  {
    Icon: IconLock,
    tag: "Privacy",
    title: "Stealth-address routing",
    desc: "Every payment uses a fresh one-time stealth address generated by Cloak. No observer can link sender to recipient or infer any salary amount.",
  },
  {
    Icon: IconKey,
    tag: "Compliance",
    title: "Auditable by choice",
    desc: "After every batch you receive a cryptographic viewing key. Share it with your accountant at audit time — nothing else is ever exposed.",
  },
  {
    Icon: IconBolt,
    tag: "Speed",
    title: "One-click batch send",
    desc: "Upload a CSV, review, disburse. All recipients handled in a single shielded transaction. Fast, cheap, and private on Solana Devnet.",
  },
] as const;

const STEPS = [
  {
    num: "01",
    title: "Upload your payroll CSV",
    desc: "Drag in your roster — wallet addresses, amounts, and token types. Every address is validated on-curve before sending.",
  },
  {
    num: "02",
    title: "Send privately via Cloak",
    desc: "One click triggers a shielded batch disbursement. On-chain it appears as a single opaque transaction with no readable output amounts.",
  },
  {
    num: "03",
    title: "Export the viewing key",
    desc: "After disbursing, download a viewing key. Paste it in the Audit page anytime to unlock the full breakdown — no wallet required.",
  },
] as const;

/* ── Page ──────────────────────────────────────────────── */
export default function LandingPage() {
  return (
    <div className="relative overflow-x-hidden">
      {/* Background grid */}
      <div
        className="absolute inset-0 bg-grid pointer-events-none select-none"
        aria-hidden="true"
      />

      {/* Floating orbs */}
      <div
        className="orb absolute pointer-events-none"
        style={{
          top: "-180px",
          left: "20%",
          width: "700px",
          height: "700px",
          borderRadius: "50%",
          background:
            "radial-gradient(circle, rgba(109,40,217,0.28) 0%, transparent 65%)",
        }}
        aria-hidden="true"
      />
      <div
        className="orb orb-2 absolute pointer-events-none"
        style={{
          bottom: "0",
          right: "5%",
          width: "500px",
          height: "500px",
          borderRadius: "50%",
          background:
            "radial-gradient(circle, rgba(139,92,246,0.18) 0%, transparent 65%)",
        }}
        aria-hidden="true"
      />

      {/* ──────────────── HERO ──────────────── */}
      <section className="relative z-10 max-w-5xl mx-auto px-4 pt-24 pb-20 text-center">
        {/* Live badge */}
        <div className="badge mb-10 mx-auto w-fit" role="status">
          <span
            className="w-2 h-2 rounded-full block"
            style={{
              background: "#a78bfa",
              animation: "orb-drift 2s ease-in-out infinite",
            }}
            aria-hidden="true"
          />
          Live on Solana Devnet&nbsp;&nbsp;·&nbsp;&nbsp;Powered by Cloak Protocol
        </div>

        {/* Headline */}
        <h1
          className="font-extrabold tracking-tight leading-tight mb-6"
          style={{ fontSize: "clamp(2.6rem, 8vw, 4.5rem)" }}
        >
          <span className="text-white">Private Payroll</span>
          <br />
          <span className="gradient-text">for the Onchain Era</span>
        </h1>

        {/* Sub */}
        <p className="text-slate-400 text-lg sm:text-xl max-w-2xl mx-auto mb-10 leading-relaxed">
          On a transparent chain, every contributor can see every colleague&apos;s
          salary.{" "}
          <span className="text-white font-semibold">Shieldrexx</span> fixes
          that — zero-knowledge batch disbursements, private by default,
          auditable by choice.
        </p>

        {/* CTAs */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
          <Link href="/dashboard" className="btn-primary">
            Launch Payroll Run <span aria-hidden="true">→</span>
          </Link>
          <Link href="/audit" className="btn-secondary">
            Audit a Batch
          </Link>
        </div>

        {/* Stats strip */}
        <div
          className="inline-grid grid-cols-3 rounded-2xl overflow-hidden border"
          style={{
            borderColor: "rgba(124,58,237,0.25)",
            background: "rgba(109,40,217,0.08)",
            divideColor: "rgba(124,58,237,0.2)",
          }}
          role="list"
          aria-label="Key metrics"
        >
          {(
            [
              { num: "0", label: "On-chain exposure" },
              { num: "1-click", label: "Batch disbursement" },
              { num: "∞", label: "Recipients per run" },
            ] as const
          ).map((s, i) => (
            <div
              key={s.label}
              className="px-7 py-5"
              role="listitem"
              style={
                i > 0
                  ? { borderLeft: "1px solid rgba(124,58,237,0.2)" }
                  : undefined
              }
            >
              <p className="text-2xl font-bold gradient-text">{s.num}</p>
              <p className="text-slate-500 text-xs mt-1 whitespace-nowrap">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ─────────────── FEATURES ─────────────── */}
      <section
        className="relative z-10 max-w-5xl mx-auto px-4 pb-20"
        aria-labelledby="feat-h"
      >
        <h2 id="feat-h" className="sr-only">
          Features
        </h2>
        <div className="grid sm:grid-cols-3 gap-5">
          {FEATURES.map(({ Icon, tag, title, desc }) => (
            <article key={title} className="card rounded-2xl p-6 flex flex-col gap-4">
              <div className="flex items-center gap-3">
                <div
                  className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0"
                  style={{
                    background: "rgba(109,40,217,0.15)",
                    border: "1px solid rgba(124,58,237,0.3)",
                  }}
                  aria-hidden="true"
                >
                  <Icon />
                </div>
                <span className="step-num uppercase tracking-widest">{tag}</span>
              </div>
              <div>
                <h3 className="text-white font-semibold text-base mb-2">{title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{desc}</p>
              </div>
            </article>
          ))}
        </div>
      </section>

      {/* ──────────── HOW IT WORKS ──────────── */}
      <section
        className="relative z-10 max-w-5xl mx-auto px-4 pb-24"
        aria-labelledby="how-h"
      >
        <div className="text-center mb-14">
          <p className="step-num uppercase tracking-widest mb-3">How it works</p>
          <h2
            id="how-h"
            className="text-3xl sm:text-4xl font-bold text-white"
          >
            Three steps. Total privacy.
          </h2>
        </div>

        <div className="grid sm:grid-cols-3 gap-8 relative">
          {/* Connector (decorative) */}
          <div
            className="hidden sm:block absolute top-7 left-[20%] right-[20%] h-px"
            style={{
              background:
                "linear-gradient(90deg, transparent, rgba(124,58,237,0.4), transparent)",
            }}
            aria-hidden="true"
          />

          {STEPS.map(({ num, title, desc }) => (
            <div
              key={num}
              className="flex flex-col items-center text-center gap-4"
            >
              <div
                className="relative z-10 w-14 h-14 rounded-full flex items-center justify-center"
                style={{
                  background: "rgba(40,20,80,0.9)",
                  border: "1px solid rgba(124,58,237,0.5)",
                  boxShadow: "0 0 24px rgba(124,58,237,0.25)",
                }}
                aria-label={`Step ${num}`}
              >
                <span className="step-num">{num}</span>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-2">{title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ─────────────── BOTTOM CTA ─────────────── */}
      <section className="relative z-10 max-w-5xl mx-auto px-4 pb-28">
        <div
          className="card rounded-3xl p-10 sm:p-16 text-center"
          style={{
            background:
              "linear-gradient(135deg, rgba(13,18,48,0.95) 0%, rgba(50,20,90,0.5) 100%)",
          }}
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Ready for your first private payroll?
          </h2>
          <p className="text-slate-400 max-w-md mx-auto mb-8 leading-relaxed">
            Connect your Phantom wallet on Devnet and run a full private batch
            disbursement in under two minutes.
          </p>
          <Link href="/dashboard" className="btn-primary">
            Get Started <span aria-hidden="true">→</span>
          </Link>
        </div>
      </section>
    </div>
  );
}
